"""audit-trail tamper evidence: hash-chain the append-only event tables.

Each row of order_events, agent_decisions, and system_events is stamped at
insert (database trigger, so EVERY writer is covered) with::

    prev_hash = row_hash of the previous row (or 'GENESIS')
    row_hash  = sha256(prev_hash || canonical_jsonb(row minus hash columns))

Any post-hoc UPDATE or DELETE breaks the chain arithmetic even if the
append-only triggers are bypassed (superuser, buggy migration, external
compromise). Canonicalization is jsonb text under an explicit UTC timezone
GUC so insert-time and verification-time serialization are identical.
``audit_chain_breaks(regclass)`` recomputes the whole chain server-side.

This protects against accidental corruption, buggy migrations, and database
compromise; the HMAC anchors that make the chain *unforgeable* live in
application code with the key held OUTSIDE the database (Section 17) — see
src/persistence/audit_chain.py.

Also extends the m0008-style append-only enforcement to agent_decisions and
system_events (order_events already has it).
"""

from __future__ import annotations

from alembic import op

revision = "0015"
down_revision = "0014"
branch_labels = None
depends_on = None

CHAINED_TABLES = ("order_events", "agent_decisions", "system_events")


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS pgcrypto")

    for table in CHAINED_TABLES:
        op.execute(
            f"""
            ALTER TABLE {table}
                ADD COLUMN chain_seq BIGINT GENERATED BY DEFAULT AS IDENTITY,
                ADD COLUMN prev_hash TEXT,
                ADD COLUMN row_hash TEXT
            """
        )
        op.execute(f"CREATE INDEX ix_{table}_chain_seq ON {table} (chain_seq)")

    # One generic stamping function; timezone pinned so jsonb text rendering of
    # timestamptz values is identical at insert and verification time.
    op.execute(
        """
        CREATE FUNCTION audit_chain_stamp() RETURNS trigger
        LANGUAGE plpgsql
        SET timezone TO 'UTC'
        AS $$
        DECLARE prev TEXT;
        BEGIN
            EXECUTE format(
                'SELECT row_hash FROM %I ORDER BY chain_seq DESC LIMIT 1',
                TG_TABLE_NAME
            ) INTO prev;
            NEW.prev_hash := COALESCE(prev, 'GENESIS');
            NEW.row_hash := encode(
                digest(
                    NEW.prev_hash || (to_jsonb(NEW) - 'row_hash' - 'prev_hash')::text,
                    'sha256'
                ),
                'hex'
            );
            RETURN NEW;
        END $$
        """
    )

    op.execute(
        """
        CREATE FUNCTION audit_chain_breaks(tbl regclass)
        RETURNS TABLE(
            chain_seq BIGINT,
            expected_prev TEXT,
            stored_prev TEXT,
            recomputed_hash TEXT,
            stored_hash TEXT
        )
        LANGUAGE plpgsql
        SET timezone TO 'UTC'
        AS $$
        BEGIN
            RETURN QUERY EXECUTE format($f$
                SELECT * FROM (
                    SELECT t.chain_seq,
                           COALESCE(
                               lag(t.row_hash) OVER (ORDER BY t.chain_seq),
                               'GENESIS'
                           ) AS expected_prev,
                           t.prev_hash AS stored_prev,
                           encode(
                               digest(
                                   t.prev_hash ||
                                   (to_jsonb(t) - 'row_hash' - 'prev_hash')::text,
                                   'sha256'
                               ),
                               'hex'
                           ) AS recomputed_hash,
                           t.row_hash AS stored_hash
                    FROM %s t
                ) x
                WHERE x.recomputed_hash IS DISTINCT FROM x.stored_hash
                   OR x.expected_prev IS DISTINCT FROM x.stored_prev
                ORDER BY x.chain_seq
            $f$, tbl);
        END $$
        """
    )

    for table in CHAINED_TABLES:
        op.execute(
            f"""
            CREATE TRIGGER trg_{table}_chain
            BEFORE INSERT ON {table}
            FOR EACH ROW EXECUTE FUNCTION audit_chain_stamp()
            """
        )

    # Append-only enforcement for the two tables that did not yet have it.
    for table in ("agent_decisions", "system_events"):
        op.execute(
            f"""
            CREATE FUNCTION {table}_append_only() RETURNS trigger
            LANGUAGE plpgsql AS $$
            BEGIN
                RAISE EXCEPTION '{table} is append-only (audit trail)';
            END $$
            """
        )
        op.execute(
            f"""
            CREATE TRIGGER trg_{table}_append_only
            BEFORE UPDATE OR DELETE ON {table}
            FOR EACH ROW EXECUTE FUNCTION {table}_append_only()
            """
        )


def downgrade() -> None:
    for table in ("agent_decisions", "system_events"):
        op.execute(f"DROP TRIGGER trg_{table}_append_only ON {table}")
        op.execute(f"DROP FUNCTION {table}_append_only()")
    for table in CHAINED_TABLES:
        op.execute(f"DROP TRIGGER trg_{table}_chain ON {table}")
        op.execute(f"DROP INDEX ix_{table}_chain_seq")
        op.execute(
            f"ALTER TABLE {table} DROP COLUMN chain_seq, "
            "DROP COLUMN prev_hash, DROP COLUMN row_hash"
        )
    op.execute("DROP FUNCTION audit_chain_breaks(regclass)")
    op.execute("DROP FUNCTION audit_chain_stamp()")
